//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_product_banner
    {
        public int id { get; set; }
        public Nullable<int> idCategory { get; set; }
        public Nullable<int> idGroupBanner { get; set; }
        public string Note { get; set; }
    
        public virtual picture_group picture_group { get; set; }
        public virtual product_category product_category { get; set; }
    }
}
