//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inbox
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string message { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> groupid { get; set; }
        public string subject { get; set; }
        public string address { get; set; }
        public string note { get; set; }
    
        public virtual group_inbox group_inbox { get; set; }
    }
}
