//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<bool> active { get; set; }
        public string images { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<int> group_menu { get; set; }
        public Nullable<int> style { get; set; }
        public string code { get; set; }
        public string note { get; set; }
        public Nullable<int> parent { get; set; }
        public string lang { get; set; }
    
        public virtual menu_group menu_group { get; set; }
    }
}
