//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class news
    {
        public int id { get; set; }
        public string name { get; set; }
        [AllowHtml]
        public string desciption { get; set; }
        [AllowHtml]
        public string content1 { get; set; }
        [AllowHtml]
        public string content2 { get; set; }
        [AllowHtml]
        public string content3 { get; set; }
        [AllowHtml]
        public string content4 { get; set; }
        [AllowHtml]
        public string content5 { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_keywords { get; set; }
        public string images { get; set; }
        public string datecreate { get; set; }
        public string dateend { get; set; }
        public string dateedit { get; set; }
        public Nullable<int> usercreate { get; set; }
        public Nullable<int> useredit { get; set; }
        public Nullable<bool> actived { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> parent { get; set; }
        public string tags { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> rating { get; set; }
        public string code { get; set; }
        public string url { get; set; }
        public string price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string lang { get; set; }
    
        public virtual news_category news_category { get; set; }
    }
}
