//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int id { get; set; }
        public string name { get; set; }
        public string filename { get; set; }
        public Nullable<int> group_picture { get; set; }
        public Nullable<bool> active { get; set; }
        public string note { get; set; }
    
        public virtual picture_group picture_group { get; set; }
    }
}
