//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_picture
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public string filename { get; set; }
        public string title { get; set; }
        public Nullable<bool> active { get; set; }
        public string lang { get; set; }
    }
}
