//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_member
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password_user { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string birthday { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> group_user { get; set; }
        public string datecreate { get; set; }
    
        public virtual user_group user_group { get; set; }
    }
}
