//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDEV.Areas.admincp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_group()
        {
            this.user_member = new HashSet<user_member>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<bool> active { get; set; }
        public string permission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_member> user_member { get; set; }
    }
}
